IMAGE_UBUNTU_2004 = "ubuntu"

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  #App server
  config.vm.define "app" do |app|
    app.vm.hostname = "appserver"
    app.vm.box = IMAGE_UBUNTU_2004
    app.vm.network :private_network, ip: "192.168.56.11"
  end

  #DB server
  config.vm.define "db" do |db|
    db.vm.hostname = "dbserver"
    db.vm.box = IMAGE_UBUNTU_2004
    db.vm.network :private_network, ip: "192.168.56.12"
  end

  #Mail server
  config.vm.define "mail" do |mail|
    mail.vm.hostname = "mailserver"
    mail.vm.box = IMAGE_UBUNTU_2004
    mail.vm.network :private_network, ip: "192.168.56.13"
  end

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
     vb.cpus = 1
  config.ssh.username = "vagrant"
  config.ssh.password = "P@ssw0rd"
  config.ssh.insert_key = false
  end
end
